# ────────────────────────────────────────────────────────────────────
# Global settings
# ────────────────────────────────────────────────────────────────────
database_url    = "postgres://user:pass@db:5432/osint?sslmode=disable"
ingest_interval = "1h"                     # human-readable (parsed by humantime_serde)
server_bind     = "0.0.0.0:9100"           # metrics & health HTTP endpoint

# ───────────────────────────────────────────────────────────────────────────────
# Feed sources
# ───────────────────────────────────────────────────────────────────────────────
[[feeds]]
name      = "CISA Cybersecurity Alerts (US-CERT)"
url       = "https://us-cert.cisa.gov/ncas/alerts.xml"
feed_type = "official"
tags      = ["threat-alerts", "vulnerabilities"]

[[feeds]]
name      = "CISA Vulnerability Advisories"
url       = "https://www.cisa.gov/cybersecurity-advisories/all.xml"
feed_type = "official"
tags      = ["vulnerabilities", "patches"]

[[feeds]]
name      = "UK NCSC Updates"
url       = "https://www.ncsc.gov.uk/api/1/services/v1/all-rss-feed.xml"
feed_type = "official"
tags      = ["advisories", "guidance"]

[[feeds]]
name      = "SANS Internet Storm Center Diaries"
url       = "https://isc.sans.edu/rssfeed_full.xml"
feed_type = "community"
tags      = ["analysis", "daily-threat"]

