

networks:
  osint_net:

volumes:
  db_data:
  grafana_data:

services:
  db:
    image: postgres:13
    container_name: osint_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: osint
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - osint_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - osint_net

  rust_ingestor:
    build: .
    image: rust_feed_ingestor:latest
    container_name: rust_ingestor
    depends_on:
      - db
    environment:
      APP__DATABASE_URL: "postgres://user:pass@db:5432/osint?sslmode=disable"
      APP__INGEST_INTERVAL: "1m"
      APP__SERVER_BIND: "0.0.0.0:9100"
      RUST_LOG: "rust_feed_ingestor=info,sqlx=warn"
    ports:
      - "9100:9100"
    networks:
      - osint_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - rust_ingestor
    networks:
      - osint_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s"
      GF_INSTALL_PLUGINS: "yesoreyeram-infinity-datasource, grafana-llm-app"
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - osint_net

  postgrest:
    image: postgrest/postgrest:latest
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./postgrest.conf:/etc/postgrest.conf:ro
    command: ["postgrest", "/etc/postgrest.conf"]
    ports:
      - "3001:3000"
    networks:
      - osint_net
